_homepage:
    path:     /
    defaults: { _controller: B2MainBundle:Default:index }

# category/subcategory(question type) listing
main_list:
    path:     /listing
    defaults: { _controller: B2MainBundle:Default:listing }

# Category page listing
main_catType:
  path:     /show/{cat}{optionalSlash}
  defaults: { _controller: B2MainBundle:Default:catListing }
  requirements: { optionalSlash : /*}

# Test page setting
main_testType:
   path:     /show/{cat}/{type}{optionalSlash}
   defaults: { _controller: B2MainBundle:Test:setTesting }
   requirements: { optionalSlash : /*}

main_sample_test:
   path:     /sample/{cat}/{type}{optionalSlash}
   defaults: { _controller: B2MainBundle:Test:sampleTest }
   requirements: { optionalSlash : /*}

# Test page stored to different table
set_question:
   path:     /test/start
   defaults: { _controller: B2MainBundle:Test:setQuestion }

# start the test
test_start:
   path:     /test
   defaults: { _controller: B2MainBundle:Test:test }

# submit Answer
answer_submit:
    path:     /test/submit
    defaults: { _controller: B2MainBundle:Test:submit }

# test over
test_over:
    path:     /test/result
    defaults: { _controller: B2MainBundle:Test:result }

