_homepage:
    path:     /
    defaults: { _controller: B2MainBundle:Default:index }

# category/subcategory(question type) listing
main_list:
    path:     /listing
    defaults: { _controller: B2MainBundle:Default:listing }

# Category page listing
main_catType:
  path:     /test/{cat}/
  defaults: { _controller: B2MainBundle:Default:catListing }

# Test page setting
main_testType:
   path:     /test/{cat}/{type}
   defaults: { _controller: B2MainBundle:Test:setTesting }

# Test page stored to different table
set_question:
   path:     /test/start
   defaults: { _controller: B2MainBundle:Test:setQuestion }

# start the test
test_start:
   path:     /test
   defaults: { _controller: B2MainBundle:Test:test }

# submit Answer
answer_submit:
    path:     /test/submit
    defaults: { _controller: B2MainBundle:Test:submit }
# test over
test_over:
    path:     /test/result
    defaults: { _controller: B2MainBundle:Test:result }

#evaluation
#  path:     /test/evaluation

#result
# path : /result
