account_register:
    path:     /register23
    defaults: { _controller: B2AccountBundle:Account:register }

account_login:
    path:     /login23
    defaults: { _controller: B2AccountBundle:Account:login }

b2_account_show:
    path:     /account/show
    defaults: { _controller: B2AccountBundle:Account:show }

login_check:
    path:    /login_check23