parameters:
#    b2_account.example.class: B2\AccountBundle\Example

services:
#    b2_account.example:
#        class: %b2_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
