imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @B2AccountBundle/Resources/config/services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ B2MainBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: "C:\\Program Files\\nodejs\\node.exe"
            node_paths: ["C:\\Users\\Chinmay\\AppData\\Roaming\\npm\\node_modules"]
            apply_to: "\.less$"
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js'
            output: js/jquery.js
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js'
            output: js/bootstrap.js
        bootstrap_less:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less'
            filters: [less,cssrewrite]
            output: css/bootstrap.css
        fontawesome_css:
            inputs:
                - '%kernel.root_dir%/../vendor/fontawesome/fontawesome/less/font-awesome.less'
            filters: [less, cssrewrite]
            output: css/fontawesome.css
        font-awesome-otf:
            inputs: '%kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/FontAwesome.otf'
            output: 'fonts/FontAwesome.otf'
        font-awesome-eot:
            inputs: '%kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.eot'
            output: 'fonts/fontawesome-webfont.eot'
        font-awesome-svg:
            inputs: '%kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.svg'
            output: 'fonts/fontawesome-webfont.svg'
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.ttf'
            output: 'fonts/fontawesome-webfont.ttf'
        font-awesome-woff:
            inputs: '%kernel.root_dir%/../vendor/fontawesome/fontawesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        zither_less:
            inputs: '@B2MainBundle/Resources/public/less/style.less'
            output: css/style.css
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# mongodb
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: test_ump4
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags: [{ name: 'twig.extension' }]

fos_user:
    db_driver: mongodb # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: B2\AccountBundle\Document\User
    registration:
        form:
            type: b2_user_registration